###
POST http://localhost:8765/authorities/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "name": "MODERATOR"
}

###
PUT http://localhost:8765/authorities/edit
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 3,
  "name": "MODERATOR-ADMIN"
}

###
POST http://localhost:8765/identities/create
Content-Type: application/json

{
  "username": "somebody",
  "password": "somebody",
  "email": "somebody@gmail.com"
}

###
PUT http://localhost:8765/identities/edit
Content-Type: application/json
Authorization: Basic somebody somebody

{
  "id": 3,
  "username": "somebody777",
  "email": "somebody777@gmail.com"
}

###
GET http://localhost:8765/identities
Content-Type: application/json
Authorization: Basic admin admin

###
@username = somebody
GET http://localhost:8765/identities/{{username}}
Content-Type: application/json
Authorization: Basic admin admin

###
PUT http://localhost:8765/identities/edit
Content-Type: application/json
Authorization: Basic user user

{
  "id": 2,
  "username": "user222",
  "email": "user222@mail.ru"
}

###
DELETE http://localhost:8765/identities/delete?identityId=2
Content-Type: application/x-www-form-urlencoded
Authorization: Basic user user

###
@author-id = 1
GET http://localhost:8765/books/by-author/{{author-id}}
Content-Type: application/json

###
@genre-id = 1
GET http://localhost:8765/books/by-genre/{{genre-id}}
Content-Type: application/json

###
GET http://localhost:8765/genres
Content-Type: application/json

###
GET http://localhost:8765/genres/{{genre-id}}
Content-Type: application/json

###
POST http://localhost:8765/genres/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "name": "Фантастика"
}

###
PUT http://localhost:8765/genres/edit
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 2,
  "name": "Детектив"
}

###
GET http://localhost:8765/authors
Content-Type: application/json

###
GET http://localhost:8765/authors/{{author-id}}
Content-Type: application/json

###
POST http://localhost:8765/authors/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "firstname": "asdqwe",
  "lastname": "gfhhjg",
  "patronymic": "tyiutyiti"
}

###
PUT http://localhost:8765/authors/edit
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 2,
  "firstname": "qqqqqqq",
  "lastname": "ssssssss",
  "patronymic": "aaaaaaaa"
}

###
POST http://localhost:8765/books/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "title": "QWE",
  "pages": 200,
  "description": "qwertyuio",
  "authorId": 1,
  "genreId": 1
}

###
PUT http://localhost:8765/books/edit
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 3,
  "title": "QWERTY",
  "pages": 350,
  "description": "qwertyuioASD",
  "authorId": 1,
  "genreId": 1
}

###
POST http://localhost:8765/subscriptions/create
Content-Type: application/json
Authorization: Basic user user

{
  "title": "user-sub",
  "identityId": 2
}

###
@subscription-id = 1
GET http://localhost:8765/subscriptions/{{subscription-id}}
Content-Type: application/json
Authorization: Basic admin admin

###
@identity-id = 1
GET http://localhost:8765/subscriptions/identity/{{identity-id}}
Content-Type: application/json
Authorization: Basic admin admin

###
GET http://localhost:8765/payment-types
Content-Type: application/json

###
@paymentType-id = 2
GET http://localhost:8765/payment-types/{{paymentType-id}}
Content-Type: application/json

###
POST http://localhost:8765/payment-types/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 0,
  "name": "Paypal"
}

###
PUT http://localhost:8765/payment-types/edit
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 3,
  "name": "World"
}

###
GET http://localhost:8765/payments
Content-Type: application/json
Authorization: Basic admin admin

###
@payment-id = 1
GET http://localhost:8765/payments/{{payment-id}}
Content-Type: application/json
Authorization: Basic admin admin

###
POST http://localhost:8765/payments/make-payment
Content-Type: application/json
Authorization: Basic user user

{
  "identityId": 2,
  "paymentTypeId": 2,
  "subscriptionId": 2
}

###
POST http://localhost:8765/subscriptions/add-book?bookId=2
Content-Type: application/json
Authorization: Basic user user

{
  "id": 2,
  "title": "user-sub",
  "identityId": 2
}