###
POST http://localhost:8765/authorities/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 0,
  "name": "MODERATOR"
}

###
POST http://localhost:8765/identities/create
Content-Type: application/json

{
  "id": 0,
  "username": "somebody",
  "password": "somebody",
  "email": "somebody@gmail.com"
}

###
PUT http://localhost:8765/identities/edit
Content-Type: application/json
Authorization: Basic somebody somebody

{
  "id": 3,
  "username": "somebody777",
  "email": "somebody777@gmail.com"
}

###
GET http://localhost:8765/identities
Content-Type: application/json
Authorization: Basic admin admin

###
@username = somebody
GET http://localhost:8765/identities/{{username}}
Content-Type: application/json
Authorization: Basic admin admin

###
PUT http://localhost:8765/identities/edit
Content-Type: application/json
Authorization: Basic user user

{
  "id": 2,
  "username": "user222",
  "email": "user222@mail.ru"
}

###
DELETE http://localhost:8765/identities/delete?identityId=2
Content-Type: application/x-www-form-urlencoded
Authorization: Basic user user

###
POST http://localhost:8765/subscriptions/create
Content-Type: application/json
Authorization: Basic user user

{
  "Id": 0,
  "title": "user-sub",
  "identityId": 2
}

###
PUT http://localhost:8765/subscriptions/edit
Content-Type: application/json
Authorization: Basic user user

{
  "id": 2,
  "title": "user-subscription",
  "identityId": 2
}

###
@subscription-id = 1
GET http://localhost:8765/subscriptions/{{subscription-id}}
Content-Type: application/json
Authorization: Basic admin admin

###
@identity-id = 1
GET http://localhost:8765/subscriptions/identity/{{identity-id}}
Content-Type: application/json
Authorization: Basic admin admin

###
POST http://localhost:8765/subscriptions/add-book?bookId=2
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 1,
  "title": "admin-sub",
  "identityId": 1
}

###
@author-id = 1
GET http://localhost:8765/books/by-author/{{author-id}}
Content-Type: application/json

###
@genre-id = 1
GET http://localhost:8765/books/by-genre/{{genre-id}}
Content-Type: application/json

###
GET http://localhost:8765/genres
Content-Type: application/json

###
GET http://localhost:8765/genres/{{genre-id}}
Content-Type: application/json

###
POST http://localhost:8765/genres/create
Content-Type: application/json

{
  "id": 0,
  "name": "Фантастика"
}

###
PUT http://localhost:8765/genres/edit
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 2,
  "name": "Детектив"
}